### ISSUE TITLE
GCP raw data 수집이 안됨

### ISSUE THREAD

**Issue by wynter122** [ddps-lab/spotlake#338]
한국 시간 기준 11월 18일 오전 6시부터 gcp 데이터 수집이 되지 않고 있음을 확인했습니다.
원인이 무엇인지 빠르게 확인해보도록 하겠습니다.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/72314987/203463376-34930ea3-55a2-48e0-9b0e-74122309e39b.png">

**Comment by wynter122** [comment]
cloudwatch의 에러 메세지는 다음과 같습니다
```
[ERROR] ConnectionError: HTTPSConnectionPool(host='cloud.google.comhttps', port=443): Max retries exceeded with url: //cloud.google.com/frame/compute/vm-instance-pricing_716c6c4c149b332c379338597e1dbdedfeb011c60c10eee04b213a93181414bf.frame (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcabb6db9a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 104, in lambda_handler
    gcp_collect(timestamp)
  File "/var/task/lambda_function.py", line 44, in gcp_collect
    table = get_table(url)
  File "/var/task/load_vminstance_pricing.py", line 34, in get_table
    response = requests.get('https://cloud.google.com' + url)
  File "/opt/python/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/opt/python/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/python/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
```

**Comment by wynter122** [comment]
에러의 원인은 vminstance pricing page 를 크롤링하는 부분에서 발생했습니다.
크롤링 단계는 다음과 같았습니다.
1. 전체 페이지에서 각 테이블에 접근 가능한 iframe url 동적으로 얻어옴 (불규칙하게 url이 바뀌기 때문)
2. iframe url을 순서대로 request 보내 데이터 수집

1번에서 iframe url을 얻어올 때, 기존에는 해당 attribute 값이 `src="vm-instance-pricing_716c6c4c149b332c379338597e1dbdedfeb011c60c10eee04b213a93181414bf.frame?hl=ko"` 로 제공되어 코드상에서 'https://cloud.google.com/compute/' + 얻어온 url 로 request를 보냈습니다.
이번에 확인해보니 attribute 값이 `src="https://cloud.google.com/frame/compute/vm-instance-pricing_716c6c4c149b332c379338597e1dbdedfeb011c60c10eee04b213a93181414bf.frame?hl=ko"` 이런 식으로 바뀌어 전체 url의 connect에 실패한것으로 파악됩니다.

**Comment by kmu-leeky** [comment]
현영아 빠르게 잘 발견했다. url 이 바뀌었구나. 우선 빠르게 수정이 가능할까?
url 의 변경이 있을수 있겠다고 생각했는데 그게 있었구나. aws 처럼 파일 수집에 대한 모니터링 모듈을 빠르게 만들어서 지속적으로 모니터링 하는 수밖에 없겠다.
그래도 gcp 는 데이터 변화가 자주 있지는 않으니 유실되는 정보도 없지 않을까 하는 기대를 ㅎㅎ

**Comment by wynter122** [comment]
네 교수님 우선 lambda 수정하였고, 테스트로 수집한 데이터 확인했을때에는 정상화 되는것을 확인했습니다. 
한국시간 기준 2시에 수집된 데이터가 s3와 timestream에 업로드되는것을 확인 한 후 수정 결과와 변경한 코드 보고드리겠습니다.

**Comment by wynter122** [comment]
네 교수님 빠르게 그 부분을 도입하는게 좋아보입니다. 
spotlake 서비스 공개 할쯤 까지는 아침마다 수집 현황을 확인했는데, 한동안 문제가 없어 확인을 소홀히 했더니 이런 일이 발생했습니다.
죄송합니다. 석현님과 에러 리포트 시스템 구현 완료 이전까지는 지속적으로 확인해보도록 하겠습니다!

**Comment by wynter122** [comment]
### GCP 수집 모듈 정상화
GCP 수집 모듈을 정상화하였고, UTC 2022년 11월 23일 오전 4시부터 수집을 다시 시작했습니다.
수집한 데이터는 기존과 같이 정상적으로 수집되고 있음을 확인했습니다. 
<img width="1478" alt="image" src="https://user-images.githubusercontent.com/72314987/203473552-ceeec385-9f4c-4b80-9378-24396bdaa63f.png">

timestream 쿼리 결과 다행히 수집이 종료된 시점과 변한 데이터가 없어서 데이터 변화 포인트는 유실되지 않았음을 확인했습니다.
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/72314987/203473647-f94d7e15-65d3-4f16-8564-165a6766789b.png">
